export const ACT_GET_ALL_PROVINCE = 'ACT_GET_ALL_PROVINCE'
export const ACT_GET_ALL_DISTRICT_BY_PROVINCE = 'ACT_GET_ALL_DISTRICT_BY_PROVINCE'
export const ACT_GET_ALL_WARD_BY_DISTRICT = 'ACT_GET_ALL_WARD_BY_DISTRICT'