export const ACT_GET_ALL_PRODUCT_PER_PAGE = 'ACT_GET_ALL_PRODUCT_PER_PAGE'
export const ACT_GET_CURRENT_PAGE = 'ACT_GET_CURRENT_PAGE'
export const ACT_GET_PRODUCT_NAME = 'ACT_GET_PRODUCT_NAME'
export const ACT_GET_PRODUCT_BY_NAME = 'ACT_GET_PRODUCT_BY_NAME'